version: "3.8"
services:
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    restart: always
  web:
    build: ./web
    volumes:
      - ./web:/app
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5001:5000"
    depends_on:
      - db
    # restart: on-failure
volumes:
  db_data:
