version: '3'
services:
  web:
    image: node:20-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run start"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
volumes:
  db_data:
