version: "3.8"
services:
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    restart: always
  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "5001:5000"
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
volumes:
  db_data:
